### ISSUE TITLE
CUDA 학습하기

### ISSUE THREAD

**Issue by bjsystems** [bjsystems/rnd-pub#1]
# CUDA 툴킷 정체 확인
- C언어 기반 GPU 핸들링 확장팩
- CPU를 그대로 GPU에 복제
- Application 단위 GPU 정비/최적화

# ref
- https://renai21c.gitbooks.io/linux-nvidia-cuda/content/chapter1.html

**Comment by TovenBae** [comment]
# CUDA(Computed Unified Device Architecture)
- 2006년 11월 NVIDIA에서 개발한 GPU 개발 툴로써 c, c++ 기반으로 짜여진 완전 기초적 H/W 접근을 해야하는데, 많은 연구자들이 딥러닝에 사용할 수 있고, 쉽게 설치할 수 있도록 오픈한 GPGPU 기술임
- 이는 [SDK](https://ko.wikipedia.org/wiki/SDK)와 [API](https://ko.wikipedia.org/wiki/API)로 프로그래머가 [C언어](https://ko.wikipedia.org/wiki/C%EC%96%B8%EC%96%B4)로 알고리즘을 기술하여 [지포스 8 시리즈](https://ko.wikipedia.org/wiki/%EC%A7%80%ED%8F%AC%EC%8A%A4_8_%EC%8B%9C%EB%A6%AC%EC%A6%88) GPU 상에서 실행시킬 수 있게 해 주는 것
- 
- 현재는 NVIDIA-Driver, CUDA, CUDNN만 설치하면 딥러닝을 쉽게 사용할 수 있음.
- CUDA는 [엔비디아](http://ko.wikipedia.org/wiki/%EC%97%94%EB%B9%84%EB%94%94%EC%95%84)가 개발해오고 있으며 이 아키텍처를 사용하려면 엔비디아 GPU와 특별한 스트림 처리 드라이버가 필요하다. CUDA는 G8X GPU로 구성된 지포스 8 시리즈급 이상에서 동작한다. CUDA는 CUDA GPU 안의 명령셋과 대용량 병렬 처리 메모리를 접근할 수 있도록 해 준다.
개발자는 패스스케일 오픈64 C 컴파일러로 컴파일 된 '쿠다를 위한 C' (C언어를 엔비디아가 확장한 것) 를 사용하여 GPU 상에서 실행시킬 알고리듬을 작성할 수 있다.

### 사용이유
- 많은 양의 연산을 동시에 처리하기 위함, 예) 딥러닝, 채널과 같은 수학적 계산에 활용
- 기존의 컴퓨터 연산은 CPU + RAM을 사용하여 연산(예, 미분) . CPU를 이용한 연산은 대부분 Single-Core를 사용하고 MultiProcessing, Multi-Threading을 이용하여 CPU가 보유한 코어 개수만큼의 Multi-Core를 이용하여 연산 수행. 일반적인 딥러닝, 특히 pytouch 나 thnsorflow에서 data loader파트에서, core갯수를 주고 데이터 loading하는 부분이 이에 해당함.
- 이에 반해 GPU의 Core수는 엄청남. CPU는 8~32개인데 비해 GPU는 몇 천개 이상이며 이를 이용한 Many-Code dependent 연산 진행, Video RAM에 있는 데이터 연산 수행
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/7900446/228117983-00121237-ed10-42d0-ae5f-5864d3f798f2.png">
- 예, 딥러닝에서 연산은 행렬 연산을 수행함. 4x4 행렬연산의 경우 CPU를 이용한 연산은 16번 수행, 병렬 연산의 경우 1번에 처리. CPU가 GPU 속도의 2배라 가정하면, CPU로 연산시 8시간 걸릴경우(0.5x16) GPU연산은 1시간 걸림(1x1)

### CUDA 장점
1. 흩뿌린 읽기 : 코드가 메모리의 임의 위치에서 데이터를 읽을 수 있다.
2. 공유 메모리 : 쿠다는 고속 공유 메모리 지역(16 or 48kb)을 드러내어 스레드 간에 나눌 수 있게 해준다. 이는 사용자 관리 캐시로 사용될 수 있는데, 텍스처 룩업을 이용하는 경우 보다 더 빠른 대역폭이 가능해진다.
3. 디바이스 상의 읽기, 쓰기가 호스트보다 더 빠르다
4. 정수와 비트 단위 연산을 충분히 지원한다. 정수 텍스처 룩업이 포함된다.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/7900446/228120993-5cff36c6-a2cd-466f-9379-851042189dc4.png">


### GPGPU(General-Purpose computing on Graphics Processing Units, GPU상의 범용계산)
- 일반적으로 컴퓨터 그래픽를 위한 계산에만 사용하는 그래픽 처리 장치(GPU)를 중앙처리장치(CPU)의 응용 프로그램 계산에 사용하는 기술
- 흐름처리(stream processing)를 이용해서 풀 수 있는 문제에 효과적이며 최근에 기술 발전 덕분에 처리 가능한 문제의 종류가 늘고 있다.
- 
##### 흐름처리
GPU는 독립적인 꼭짓점들과 프래그먼트만 처리할 수 있지만 다수를 병렬로 처리할 수 있다. 이것은 특히 프로그래머가 같은 방식으로 많은 수의 꼭짓점 또는 프래그먼트를 처리하고자 할 때 유용하다. 이런 의미에서, GPU는 흐름 프로세서이다. 즉, 병렬로 한번에 하나의 [커널](https://ko.wikipedia.org/wiki/%EC%BB%A4%EB%84%90)을 흐름 속의 많은 레코드에 실행시키는 것이다. 흐름이란 단순히 유사한 계산을 필요로 하는 레코드의 모음이다. 흐름으로 데이터 병렬성을 구할 수 있다

ref
- https://kaen2891.tistory.com/20
- https://ko.wikipedia.org/wiki/GPGPU

**Comment by TovenBae** [comment]
금일학습
- CUDA 개념 추가 학습 정리

**Comment by TovenBae** [comment]
금일학습

- CUDA 개념 추가 학습 정리

**Comment by TovenBae** [comment]
금일학습
- 샘플 모듈 개발

**Comment by TovenBae** [comment]
https://renai21c.gitbooks.io/linux-nvidia-cuda/content/chapter1.html

https://blogs.nvidia.co.kr/2018/01/16/cuda-toolkit/

https://hiuaa.tistory.com/39

**Comment by TovenBae** [comment]
금일작업
- toast에 instance 구성 후 샘플 코드 작성
